name: Run

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Verify Python version
        run: python --version  # Confirm Python version

      - name: Install dependencies
        run: |
          echo "Checking for requirements.txt file..."
          if [ -f requirements.txt ]; then
            echo "Installing dependencies from requirements.txt"
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping dependency installation."
          fi

      - name: Run Python script
        run: |
          echo "Starting Python script..."
          python main.py

      - name: Commit and push last_message_id.txt
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add last_message_id.txt
          git commit -m "Update last_message_id.txt"
          git push
